stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - echo "Installing NPM Dependencies and running Angular Application"
  script:
#Kill existing process
    #- fuser -k 4200/tcp
#Install dependencies
    - npm install 
#Run ng serve/ start angular project
    - nohup ng serve --host 0.0.0.0 </dev/null &>/dev/null &
#Obtain Public IP to browse
    - wget -qO- https://ipecho.net/plain ; echo
  tags:
    - frontend
  only:
    - master
  cache:
    key: install-cache
    paths:
      - node_modules/


